# Generated by Django 4.2 on 2023-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='descricao',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='fim',
            field=models.DateTimeField(verbose_name='Data para a o fim da votacao'),
        ),
    ]
