# Generated by Django 4.2 on 2023-04-20 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0002_alter_eleicao_descricao_alter_eleicao_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='participantes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
