# Generated by Django 4.2 on 2023-04-20 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0003_alter_eleicao_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='participantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='total_de_votos',
            field=models.IntegerField(default=0, verbose_name='Total de votos'),
        ),
    ]
