# Generated by Django 4.2 on 2023-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_alter_eleicao_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleicao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Media'),
        ),
    ]
