# Generated by Django 4.2 on 2023-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_eleicao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='foto',
            field=models.ImageField(upload_to='Media'),
        ),
    ]
