# Generated by Django 4.2 on 2023-04-20 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0006_alter_eleicao_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleicao',
            name='participantes',
        ),
        migrations.AddField(
            model_name='eleicao',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
