# Generated by Django 4.2 on 2023-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_de_votos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de votos'),
        ),
    ]
